services:
  connect-gnu-node:
    container_name: connect-gnu-node
    build:
      context: .
      target: build
    ports:
      - '5200:5001'
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    env_file:
      - .env.dev
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: pnpm start:dev

volumes:
  node_modules:
