x-defaults: &common-settings
  build:
    context: .
    dockerfile: Dockerfile.dev # 개발 환경 도커파일 마운트
  volumes:
    - ./.env.dev:/app/.env # 개발 환경 변수 마운트
  networks:
    - connect-gnu-network
services:
  connect-gnu-node-blue:
    <<: *common-settings
    container_name: connect-gnu-node-blue
    ports:
      - '5200:5001'

  connect-gnu-node-green:
    <<: *common-settings
    container_name: connect-gnu-node-green
    ports:
      - '5201:5001'

networks:
  connect-gnu-network:
    external: true
