server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: docker

    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 5s

    relabel_configs:
      # 로그를 수집하지 않을 컨테이너
      - source_labels:
          [__meta_docker_container_label_com_docker_compose_service]
        regex: '(loki|promtail|grafana|certbot)'
        action: drop

      # 컨테이너 이름 정리 (/ 제거)
      - source_labels: ['__meta_docker_container_name']
        regex: '/(.*)'
        target_label: container

      # 이미지 이름 라벨 추가
      - source_labels: ['__meta_docker_container_image']
        target_label: image

      # compose 서비스명 (docker-compose 쓸 때 유용)
      - source_labels:
          ['__meta_docker_container_label_com_docker_compose_service']
        target_label: service

    pipeline_stages:
      - docker: {}
