upstream app {
  server app:3000;
}

upstream grafana {
  server grafana:3000;
}

# HTTP 설정
server {
  listen 80;
  server_name connectgnu.kro.kr;
  underscores_in_headers    on;

  location / {
    return 301 https://$host$request_uri;
  }

  # Let's Encrypt 인증서 발급을 위한 설정
  location /.well-known/acme-challenge/ {
    allow all;
    root /var/www/certbot;
  }
}

# HTTPS 설정
server {
  listen 443 ssl;

  server_name connectgnu.kro.kr;
  underscores_in_headers    on;

  location /api {
    proxy_pass http://app;
    proxy_pass_request_headers    on;
    proxy_set_header X-Forwarded-For             $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto https;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header HOST $http_host;
    proxy_set_header X-NginX-Proxy true;

    # 백엔드 타임아웃 설정
    proxy_connect_timeout 4s;
    proxy_read_timeout 4s;
    error_page 502 = @timeout_response;
    error_page 503 = @timeout_response;
    error_page 504 = @timeout_response;

    # 카카오 챗봇 IP 주소만 허용
    allow 219.249.231.0/24;
    allow 210.121.177.238;

    # 나머지 IP 주소는 모두 차단
    deny all;
  }

  location /grafana {
    proxy_pass http://grafana;
    proxy_pass_request_headers    on;
    proxy_set_header X-Forwarded-For             $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto https;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header HOST $http_host;
    proxy_set_header X-NginX-Proxy true;
  }

  location / {
    deny all;
  }

  # 타임아웃 응답 내용
  location @timeout_response {
        default_type application/json;
        return 200 '{"version":"2.0","template":{"outputs":[{"simpleText":{"text":"서비스가 지연되고 있어요. 잠시 후 다시 시도해주세요."}}]}}';
  }

  ssl_certificate /etc/letsencrypt/live/connectgnu.kro.kr-0001/fullchain.pem;
  ssl_certificate_key /etc/letsencrypt/live/connectgnu.kro.kr-0001/privkey.pem;
  include /etc/letsencrypt/options-ssl-nginx.conf;
  ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;
}