services:
  nginx:
    image: nginx:1.29.5-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/dev.conf:/etc/nginx/conf.d/default.conf
    networks:
      - connect-gnu-network
    depends_on:
      - app

  app:
    build:
      context: ./app
      target: dev
    volumes:
      - ./app:/app
      - /app/node_modules
    restart: always
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=host.docker.internal
      - DB_PORT=54322
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - DB_DATABASE=postgres
      - DB_STORAGE_URL=http://host.docker.internal:54321/storage/v1/s3
    networks:
      - connect-gnu-network

networks:
  connect-gnu-network:
    driver: bridge
