apiVersion: 1

datasources:
  - name: PostgreSQL
    type: postgres
    uid: postgres
    url: ${DB_HOST}:${DB_PORT}
    user: ${DB_USERNAME}
    secureJsonData:
      password: ${DB_PASSWORD}
    jsonData:
      database: ${DB_DATABASE}
      sslmode: disable
      postgresVersion: 1500
      timescaledb: false
    editable: false
