

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;


CREATE EXTENSION IF NOT EXISTS "pgsodium";






COMMENT ON SCHEMA "public" IS 'standard public schema';



CREATE EXTENSION IF NOT EXISTS "pg_graphql" WITH SCHEMA "graphql";






CREATE EXTENSION IF NOT EXISTS "pg_stat_statements" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "pgcrypto" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "pgjwt" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "supabase_vault" WITH SCHEMA "vault";






CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA "extensions";






CREATE OR REPLACE FUNCTION "public"."update_updated_at_column"() RETURNS "trigger"
    LANGUAGE "plpgsql"
    AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$;


ALTER FUNCTION "public"."update_updated_at_column"() OWNER TO "postgres";


CREATE OR REPLACE FUNCTION "public"."upsert_date"() RETURNS "trigger"
    LANGUAGE "plpgsql"
    AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$;


ALTER FUNCTION "public"."upsert_date"() OWNER TO "postgres";


CREATE SEQUENCE IF NOT EXISTS "public"."academic_calendar_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE "public"."academic_calendar_id_seq" OWNER TO "postgres";

SET default_tablespace = '';

SET default_table_access_method = "heap";


CREATE TABLE IF NOT EXISTS "public"."academic_calendar" (
    "calendar_type" smallint NOT NULL,
    "end_date" "date" NOT NULL,
    "start_date" "date" NOT NULL,
    "content" "text" NOT NULL,
    "academic_id" integer DEFAULT "nextval"('"public"."academic_calendar_id_seq"'::"regclass") NOT NULL
);


ALTER TABLE "public"."academic_calendar" OWNER TO "postgres";


COMMENT ON TABLE "public"."academic_calendar" IS '학사일정 테이블';



COMMENT ON COLUMN "public"."academic_calendar"."calendar_type" IS '1: 학부생, 2: 대학원생, 3: 교직원';



CREATE TABLE IF NOT EXISTS "public"."cafeteria" (
    "id" bigint NOT NULL,
    "cafeteria_name_ko" character varying NOT NULL,
    "campus_id" bigint NOT NULL,
    "mi" integer NOT NULL,
    "rest_seq" integer NOT NULL,
    "type" character varying NOT NULL,
    "sch_sys_id" character varying,
    "form_type" smallint,
    "last_date" "date",
    "thumbnail_url" "text"
);


ALTER TABLE "public"."cafeteria" OWNER TO "postgres";


CREATE SEQUENCE IF NOT EXISTS "public"."cafeteria-diet_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE "public"."cafeteria-diet_id_seq" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."cafeteria_diet" (
    "date" "date" NOT NULL,
    "day" character varying NOT NULL,
    "time" character varying NOT NULL,
    "dish_category" character varying,
    "dish_type" character varying,
    "dish_name" character varying NOT NULL,
    "cafeteria_id" bigint NOT NULL,
    "diet_id" integer DEFAULT "nextval"('"public"."cafeteria-diet_id_seq"'::"regclass") NOT NULL
);


ALTER TABLE "public"."cafeteria_diet" OWNER TO "postgres";


COMMENT ON TABLE "public"."cafeteria_diet" IS '식당 식단 테이블';



ALTER TABLE "public"."cafeteria" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."cafeteria_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."campus" (
    "id" bigint NOT NULL,
    "campus_name_ko" character varying NOT NULL,
    "thumbnail_url" "text"
);


ALTER TABLE "public"."campus" OWNER TO "postgres";


ALTER TABLE "public"."campus" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."campus_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."college" (
    "id" bigint NOT NULL,
    "college_ko" character varying NOT NULL,
    "college_en" character varying NOT NULL,
    "etc_value" boolean DEFAULT false NOT NULL,
    "campus_id" bigint NOT NULL,
    "thumbnail_url" "text"
);


ALTER TABLE "public"."college" OWNER TO "postgres";


COMMENT ON TABLE "public"."college" IS '단과대학 정보 테이블';



ALTER TABLE "public"."college" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."college_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."department" (
    "id" bigint NOT NULL,
    "college_id" bigint NOT NULL,
    "department_ko" character varying NOT NULL,
    "department_en" character varying NOT NULL,
    "parent_department_id" bigint,
    "is_active" boolean DEFAULT true NOT NULL
);


ALTER TABLE "public"."department" OWNER TO "postgres";


COMMENT ON TABLE "public"."department" IS '학과 정보 테이블';



ALTER TABLE "public"."department" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."inmun-department_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."kakao-user" (
    "id" "text" NOT NULL,
    "department_id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"(),
    "user_type" smallint DEFAULT 1,
    "campus_id" bigint NOT NULL
);


ALTER TABLE "public"."kakao-user" OWNER TO "postgres";


COMMENT ON TABLE "public"."kakao-user" IS '유저 정보';



COMMENT ON COLUMN "public"."kakao-user"."user_type" IS '1: 학부생, 2: 대학원생, 3: 교직원, 4: 봇';



CREATE TABLE IF NOT EXISTS "public"."notice" (
    "id" integer NOT NULL,
    "category_id" integer,
    "title" "text" NOT NULL,
    "ntt_sn" integer NOT NULL,
    "created_at" "date" DEFAULT "now"()
);


ALTER TABLE "public"."notice" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."notice_category" (
    "id" integer NOT NULL,
    "department_id" integer NOT NULL,
    "category" character varying(50) NOT NULL,
    "mi" integer NOT NULL,
    "bbs_id" integer NOT NULL,
    "last_ntt_sn" integer DEFAULT 0 NOT NULL,
    "updated_at" timestamp with time zone DEFAULT "now"()
);


ALTER TABLE "public"."notice_category" OWNER TO "postgres";


CREATE SEQUENCE IF NOT EXISTS "public"."notice_category_id_seq"
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE "public"."notice_category_id_seq" OWNER TO "postgres";


ALTER SEQUENCE "public"."notice_category_id_seq" OWNED BY "public"."notice_category"."id";



CREATE SEQUENCE IF NOT EXISTS "public"."notice_id_seq"
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE "public"."notice_id_seq" OWNER TO "postgres";


ALTER SEQUENCE "public"."notice_id_seq" OWNED BY "public"."notice"."id";



CREATE TABLE IF NOT EXISTS "public"."reading_room" (
    "id" bigint NOT NULL,
    "campus_id" bigint NOT NULL,
    "library_name" character varying NOT NULL,
    "reading_room_name" character varying NOT NULL,
    "total_seats" smallint,
    "is_active" boolean DEFAULT true NOT NULL
);


ALTER TABLE "public"."reading_room" OWNER TO "postgres";


COMMENT ON TABLE "public"."reading_room" IS '열람실 정보';



ALTER TABLE ONLY "public"."notice" ALTER COLUMN "id" SET DEFAULT "nextval"('"public"."notice_id_seq"'::"regclass");



ALTER TABLE ONLY "public"."notice_category" ALTER COLUMN "id" SET DEFAULT "nextval"('"public"."notice_category_id_seq"'::"regclass");



ALTER TABLE ONLY "public"."academic_calendar"
    ADD CONSTRAINT "academic_calendar_pkey" PRIMARY KEY ("academic_id");



ALTER TABLE ONLY "public"."cafeteria_diet"
    ADD CONSTRAINT "cafeteria-diet_pkey" PRIMARY KEY ("diet_id");



ALTER TABLE ONLY "public"."cafeteria"
    ADD CONSTRAINT "cafeteria_pk" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."campus"
    ADD CONSTRAINT "campus_pk" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."college"
    ADD CONSTRAINT "college_college_en_key" UNIQUE ("college_en");



ALTER TABLE ONLY "public"."college"
    ADD CONSTRAINT "college_college_ko_key" UNIQUE ("college_ko");



ALTER TABLE ONLY "public"."college"
    ADD CONSTRAINT "college_pk" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."department"
    ADD CONSTRAINT "department_department_ko_key" UNIQUE ("department_ko");



ALTER TABLE ONLY "public"."department"
    ADD CONSTRAINT "department_pk" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."notice_category"
    ADD CONSTRAINT "notice_category_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."notice"
    ADD CONSTRAINT "notice_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."reading_room"
    ADD CONSTRAINT "reading_room_pk" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."academic_calendar"
    ADD CONSTRAINT "unique_calendar_type_content_start_date" UNIQUE ("calendar_type", "content", "start_date");



ALTER TABLE ONLY "public"."kakao-user"
    ADD CONSTRAINT "user_kakao_id_key" UNIQUE ("id");



ALTER TABLE ONLY "public"."kakao-user"
    ADD CONSTRAINT "user_pkey" PRIMARY KEY ("id");



CREATE INDEX "category_id" ON "public"."notice" USING "btree" ("category_id");



CREATE INDEX "department_id" ON "public"."notice_category" USING "btree" ("department_id");



CREATE INDEX "idx_cover" ON "public"."cafeteria_diet" USING "btree" ("date", "cafeteria_id", "time");



CREATE OR REPLACE TRIGGER "trigger_update_updated_at" BEFORE UPDATE ON "public"."notice_category" FOR EACH ROW EXECUTE FUNCTION "public"."update_updated_at_column"();



ALTER TABLE ONLY "public"."cafeteria_diet"
    ADD CONSTRAINT "cafeteria-diet_cafeteria_null_fk" FOREIGN KEY ("cafeteria_id") REFERENCES "public"."cafeteria"("id");



ALTER TABLE ONLY "public"."cafeteria"
    ADD CONSTRAINT "cafeteria_campus_null_fk" FOREIGN KEY ("campus_id") REFERENCES "public"."campus"("id");



ALTER TABLE ONLY "public"."college"
    ADD CONSTRAINT "college_campus_null_fk" FOREIGN KEY ("campus_id") REFERENCES "public"."campus"("id");



ALTER TABLE ONLY "public"."department"
    ADD CONSTRAINT "department_college_null_fk" FOREIGN KEY ("college_id") REFERENCES "public"."college"("id");



ALTER TABLE ONLY "public"."kakao-user"
    ADD CONSTRAINT "kakao-user_campus_id_fk" FOREIGN KEY ("campus_id") REFERENCES "public"."campus"("id");



ALTER TABLE ONLY "public"."notice_category"
    ADD CONSTRAINT "notice_category_department_id_fkey" FOREIGN KEY ("department_id") REFERENCES "public"."department"("id") ON UPDATE CASCADE ON DELETE RESTRICT;



ALTER TABLE ONLY "public"."notice"
    ADD CONSTRAINT "notice_category_id_fkey" FOREIGN KEY ("category_id") REFERENCES "public"."notice_category"("id") ON UPDATE CASCADE ON DELETE RESTRICT;



ALTER TABLE ONLY "public"."department"
    ADD CONSTRAINT "public_department_parent_department_id_fkey" FOREIGN KEY ("parent_department_id") REFERENCES "public"."department"("id");



ALTER TABLE ONLY "public"."reading_room"
    ADD CONSTRAINT "reading_room_campus_null_fk" FOREIGN KEY ("campus_id") REFERENCES "public"."campus"("id");



ALTER TABLE ONLY "public"."kakao-user"
    ADD CONSTRAINT "user_department_null_fk" FOREIGN KEY ("department_id") REFERENCES "public"."department"("id");





ALTER PUBLICATION "supabase_realtime" OWNER TO "postgres";


GRANT USAGE ON SCHEMA "public" TO "postgres";
GRANT USAGE ON SCHEMA "public" TO "anon";
GRANT USAGE ON SCHEMA "public" TO "authenticated";
GRANT USAGE ON SCHEMA "public" TO "service_role";




















































































































































































GRANT ALL ON FUNCTION "public"."update_updated_at_column"() TO "anon";
GRANT ALL ON FUNCTION "public"."update_updated_at_column"() TO "authenticated";
GRANT ALL ON FUNCTION "public"."update_updated_at_column"() TO "service_role";



GRANT ALL ON FUNCTION "public"."upsert_date"() TO "anon";
GRANT ALL ON FUNCTION "public"."upsert_date"() TO "authenticated";
GRANT ALL ON FUNCTION "public"."upsert_date"() TO "service_role";



























GRANT ALL ON SEQUENCE "public"."academic_calendar_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."academic_calendar_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."academic_calendar_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."academic_calendar" TO "anon";
GRANT ALL ON TABLE "public"."academic_calendar" TO "authenticated";
GRANT ALL ON TABLE "public"."academic_calendar" TO "service_role";



GRANT ALL ON TABLE "public"."cafeteria" TO "anon";
GRANT ALL ON TABLE "public"."cafeteria" TO "authenticated";
GRANT ALL ON TABLE "public"."cafeteria" TO "service_role";



GRANT ALL ON SEQUENCE "public"."cafeteria-diet_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."cafeteria-diet_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."cafeteria-diet_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."cafeteria_diet" TO "anon";
GRANT ALL ON TABLE "public"."cafeteria_diet" TO "authenticated";
GRANT ALL ON TABLE "public"."cafeteria_diet" TO "service_role";



GRANT ALL ON SEQUENCE "public"."cafeteria_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."cafeteria_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."cafeteria_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."campus" TO "anon";
GRANT ALL ON TABLE "public"."campus" TO "authenticated";
GRANT ALL ON TABLE "public"."campus" TO "service_role";



GRANT ALL ON SEQUENCE "public"."campus_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."campus_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."campus_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."college" TO "anon";
GRANT ALL ON TABLE "public"."college" TO "authenticated";
GRANT ALL ON TABLE "public"."college" TO "service_role";



GRANT ALL ON SEQUENCE "public"."college_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."college_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."college_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."department" TO "anon";
GRANT ALL ON TABLE "public"."department" TO "authenticated";
GRANT ALL ON TABLE "public"."department" TO "service_role";



GRANT ALL ON SEQUENCE "public"."inmun-department_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."inmun-department_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."inmun-department_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."kakao-user" TO "anon";
GRANT ALL ON TABLE "public"."kakao-user" TO "authenticated";
GRANT ALL ON TABLE "public"."kakao-user" TO "service_role";



GRANT ALL ON TABLE "public"."notice" TO "anon";
GRANT ALL ON TABLE "public"."notice" TO "authenticated";
GRANT ALL ON TABLE "public"."notice" TO "service_role";



GRANT ALL ON TABLE "public"."notice_category" TO "anon";
GRANT ALL ON TABLE "public"."notice_category" TO "authenticated";
GRANT ALL ON TABLE "public"."notice_category" TO "service_role";



GRANT ALL ON SEQUENCE "public"."notice_category_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."notice_category_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."notice_category_id_seq" TO "service_role";



GRANT ALL ON SEQUENCE "public"."notice_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."notice_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."notice_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."reading_room" TO "anon";
GRANT ALL ON TABLE "public"."reading_room" TO "authenticated";
GRANT ALL ON TABLE "public"."reading_room" TO "service_role";









ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "service_role";






























drop extension if exists "pg_net";


  create policy "allow all e8c111_0"
  on "storage"."objects"
  as permissive
  for select
  to authenticated, anon
using ((bucket_id = 'clicker'::text));



  create policy "allow all e8c111_1"
  on "storage"."objects"
  as permissive
  for insert
  to authenticated, anon
with check ((bucket_id = 'clicker'::text));



  create policy "allow all e8c111_2"
  on "storage"."objects"
  as permissive
  for update
  to authenticated, anon
using ((bucket_id = 'clicker'::text));



