upstream app {
  server app:3000;
  keepalive 32;
}

# HTTP 설정
server {
  listen 80;
  server_name connectgnu.kro.kr;
  underscores_in_headers    on;

  location / {
    return 301 https://$host$request_uri;
  }

  # Let's Encrypt 인증서 발급을 위한 설정
  location /.well-known/acme-challenge/ {
    allow all;
    root /var/www/certbot;
  }
}

# HTTPS 설정
server {
  listen 443 ssl http2;

  server_name connectgnu.kro.kr;
  underscores_in_headers    on;

  location /api {
    proxy_pass http://app;
    proxy_http_version 1.1;
    proxy_pass_request_headers    on;
    proxy_set_header Connection "";
    proxy_set_header X-Forwarded-For             $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto https;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header Host $http_host;
    proxy_set_header X-NginX-Proxy true;

    # 카카오 챗봇 IP 주소만 허용
    allow 219.249.231.0/24;
    allow 210.121.177.238;

    # 나머지 IP 주소는 모두 차단
    deny all;
  }

  location /api/metrics {
    proxy_pass http://app;
    proxy_http_version 1.1;
    proxy_pass_request_headers    on;
    proxy_set_header Connection "";
    proxy_set_header X-Forwarded-For             $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto https;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header Host $http_host;

    # 모니터링 인스턴스 IP만 허용
    allow 35.212.243.112;

    # 나머지 IP 주소는 모두 차단
    deny all;
  }

  location / {
    deny all;
  }

  ssl_certificate /etc/letsencrypt/live/connectgnu.kro.kr-0001/fullchain.pem;
  ssl_certificate_key /etc/letsencrypt/live/connectgnu.kro.kr-0001/privkey.pem;
  include /etc/letsencrypt/options-ssl-nginx.conf;
  ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;
}
