name: Monitoring CD

on:
  push:
    branches:
      - main
    paths:
      - "monitoring/**"
      - ".github/workflows/monitoring-cd.yml"

  workflow_dispatch:

env:
  ROOT_DIR: ./connect-gnu/monitoring

jobs:
  deploy:
    name: Deploy to Monitoring Server
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Copy files to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.MONITORING_SSH_HOST }}
          username: ${{ secrets.MONITORING_SSH_USERNAME }}
          key: ${{ secrets.MONITORING_SSH_PRIVATE_KEY }}
          source: monitoring/docker-compose.yml,monitoring/prometheus,monitoring/grafana,monitoring/nginx,monitoring/letsencrypt/init-letsencrypt.sh
          target: ${{ env.ROOT_DIR }}
          strip_components: 1

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.MONITORING_SSH_HOST }}
          username: ${{ secrets.MONITORING_SSH_USERNAME }}
          key: ${{ secrets.MONITORING_SSH_PRIVATE_KEY }}
          script: |
            cd ${{ env.ROOT_DIR }}
            docker compose pull
            docker compose up -d
            docker image prune -af
